In [2]:
import numpy as np

In [23]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
type(d)

numpy.ndarray

In [33]:
d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.96200963 0.65922931 0.58451951 0.75278005 0.59398054]
   [0.40714581 0.88881293 0.91255042 0.69521432 0.90503553]
   [0.3276567  0.32952444 0.0159108  0.96385554 0.50713231]
   [0.12688503 0.48339317 0.92596777 0.95975653 0.04422669]]

  [[0.23867875 0.60100075 0.70964029 0.72672705 0.09298947]
   [0.78552936 0.92883809 0.29945214 0.04544538 0.67899325]
   [0.95259315 0.44229622 0.13756504 0.09812686 0.39466889]
   [0.02050865 0.84064077 0.89040501 0.95009189 0.08912866]]

  [[0.66902445 0.82307407 0.81032644 0.99345518 0.83321397]
   [0.37387695 0.10554357 0.06092564 0.92490031 0.7731002 ]
   [0.79918786 0.58374184 0.74707148 0.3786134  0.0711543 ]
   [0.14567393 0.47261676 0.59232204 0.74643338 0.33839308]]]


 [[[0.7009307  0.46413459 0.21321284 0.48180958 0.67456394]
   [0.85785495 0.97822203 0.69410668 0.49656075 0.41306608]
   [0.98854056 0.85961812 0.86432982 0.47082323 0.89041145]
   [0.31689571 0.20802875 0.06167956 0.79783412 0.59996705]]

  [[0.16123856 0.12389553 0.29

In [21]:
c[0,1,2,1]

0.442296218459699

In [22]:
c[0,1,:,3]

array([0.72672705, 0.04544538, 0.09812686, 0.95009189])

In [16]:
c[0]

array([[[0.96200963, 0.65922931, 0.58451951, 0.75278005, 0.59398054],
        [0.40714581, 0.88881293, 0.91255042, 0.69521432, 0.90503553],
        [0.3276567 , 0.32952444, 0.0159108 , 0.96385554, 0.50713231],
        [0.12688503, 0.48339317, 0.92596777, 0.95975653, 0.04422669]],

       [[0.23867875, 0.60100075, 0.70964029, 0.72672705, 0.09298947],
        [0.78552936, 0.92883809, 0.29945214, 0.04544538, 0.67899325],
        [0.95259315, 0.44229622, 0.13756504, 0.09812686, 0.39466889],
        [0.02050865, 0.84064077, 0.89040501, 0.95009189, 0.08912866]],

       [[0.66902445, 0.82307407, 0.81032644, 0.99345518, 0.83321397],
        [0.37387695, 0.10554357, 0.06092564, 0.92490031, 0.7731002 ],
        [0.79918786, 0.58374184, 0.74707148, 0.3786134 , 0.0711543 ],
        [0.14567393, 0.47261676, 0.59232204, 0.74643338, 0.33839308]]])

In [7]:
x = c[0,0]
print(x)

[[0.96200963 0.65922931 0.58451951 0.75278005 0.59398054]
 [0.40714581 0.88881293 0.91255042 0.69521432 0.90503553]
 [0.3276567  0.32952444 0.0159108  0.96385554 0.50713231]
 [0.12688503 0.48339317 0.92596777 0.95975653 0.04422669]]


In [8]:
y = c[0,1]
print(y)

[[0.23867875 0.60100075 0.70964029 0.72672705 0.09298947]
 [0.78552936 0.92883809 0.29945214 0.04544538 0.67899325]
 [0.95259315 0.44229622 0.13756504 0.09812686 0.39466889]
 [0.02050865 0.84064077 0.89040501 0.95009189 0.08912866]]


In [9]:
print(np.multiply(x, y))

[[0.22961126 0.39619731 0.41479859 0.54706562 0.05523394]
 [0.31982499 0.82556331 0.27326517 0.03159428 0.61451302]
 [0.31212353 0.14574741 0.00218877 0.09458012 0.20014935]
 [0.00260224 0.40636001 0.82448633 0.9118569  0.00394187]]


In [10]:
a = np.random.random((10,4))

In [11]:
a

array([[0.33911099, 0.46288633, 0.34125099, 0.29908074],
       [0.22005496, 0.14707264, 0.89191119, 0.32138191],
       [0.78810435, 0.76593138, 0.32810478, 0.15336296],
       [0.91004695, 0.78166651, 0.69085864, 0.84093698],
       [0.55123616, 0.83357711, 0.5820751 , 0.22542277],
       [0.49020565, 0.95719117, 0.86788015, 0.82521695],
       [0.53146556, 0.61707736, 0.17484808, 0.89614151],
       [0.8114878 , 0.98458408, 0.37501791, 0.91106186],
       [0.74852014, 0.223038  , 0.70124164, 0.95322338],
       [0.06988973, 0.06396749, 0.65256393, 0.39035676]])

In [12]:
a[0]

array([0.33911099, 0.46288633, 0.34125099, 0.29908074])

In [14]:
a[:,0]

array([0.33911099, 0.22005496, 0.78810435, 0.91004695, 0.55123616,
       0.49020565, 0.53146556, 0.8114878 , 0.74852014, 0.06988973])

In [15]:
a[0,:]

array([0.33911099, 0.46288633, 0.34125099, 0.29908074])

In [25]:
a

array([[0.33911099, 0.46288633, 0.34125099, 0.29908074],
       [0.22005496, 0.14707264, 0.89191119, 0.32138191],
       [0.78810435, 0.76593138, 0.32810478, 0.15336296],
       [0.91004695, 0.78166651, 0.69085864, 0.84093698],
       [0.55123616, 0.83357711, 0.5820751 , 0.22542277],
       [0.49020565, 0.95719117, 0.86788015, 0.82521695],
       [0.53146556, 0.61707736, 0.17484808, 0.89614151],
       [0.8114878 , 0.98458408, 0.37501791, 0.91106186],
       [0.74852014, 0.223038  , 0.70124164, 0.95322338],
       [0.06988973, 0.06396749, 0.65256393, 0.39035676]])

In [27]:
np.sum(a, axis=1)

array([1.44232906, 1.5804207 , 2.03550347, 3.22350908, 2.19231113,
       3.14049393, 2.2195325 , 3.08215166, 2.62602316, 1.17677792])

In [28]:
b = np.random.random((5,2,3))

In [29]:
b

array([[[0.38973084, 0.0191002 , 0.18773652],
        [0.21464275, 0.58620038, 0.84680694]],

       [[0.53505859, 0.93952563, 0.60249901],
        [0.80177434, 0.65096396, 0.09335336]],

       [[0.50950313, 0.69543349, 0.82492723],
        [0.56307084, 0.4384564 , 0.78850934]],

       [[0.55896894, 0.05176857, 0.69742258],
        [0.42302185, 0.13644873, 0.0818405 ]],

       [[0.5625527 , 0.76655824, 0.9352826 ],
        [0.8642802 , 0.88043324, 0.24586131]]])

In [32]:
np.sum(b[0,2])
#this results in an error because b is one dimensional. When we use
#

IndexError: index 2 is out of bounds for axis 1 with size 2